In [48]:
# import statements
import numpy as np
import os
import pandas as pd
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [49]:
directory_path = "C:\gesture_recognition_by_image\manus_files"
csv_files = [file for file in os.listdir(directory_path) if file.endswith(".csv")]

In [50]:
combined_data = pd.DataFrame()

In [72]:
x = []
y = []
for idx, file in enumerate(csv_files):
    file_path = os.path.join(directory_path, file)
    df = pd.read_csv(file_path, header=0, delimiter=";", usecols=list(range(0,2))+list(range(3,367)), decimal=',')
    df = df.apply(pd.to_numeric, errors='coerce')
    x.extend(df.values)
    df['label'] = idx
    y.extend(df["label"].values)
    combined_data = combined_data._append(df, ignore_index=True)

x = np.array(x)
y = np.array(y)
from keras.utils import to_categorical

# Assuming you have 4 output classes
num_classes = 5
y_encoded = to_categorical(y, num_classes=num_classes)
y = y_encoded

In [73]:
print(x.shape)
print(y.shape)

(1410, 366)
(1410, 5)


In [74]:
print(x)

[[ 0.000000e+00  0.000000e+00  0.000000e+00 ...  2.779287e+04
   8.770906e+04  8.307434e+04]
 [ 1.000000e+00  1.600000e+01  0.000000e+00 ... -2.779287e+04
  -8.770906e+04 -8.307434e+04]
 [ 2.000000e+00  3.200000e+01  0.000000e+00 ... -1.510448e+01
  -6.179800e-02  6.179800e-02]
 ...
 [ 2.790000e+02  4.464000e+03  0.000000e+00 ...  9.644106e+01
  -3.501890e-01 -4.978200e-02]
 [ 2.800000e+02  4.480000e+03  0.000000e+00 ...  8.736361e+01
   1.055563e+02  9.473303e+01]
 [ 2.810000e+02  4.496000e+03  0.000000e+00 ... -2.471477e+02
  -3.163684e+02 -2.841047e+02]]


In [75]:
print(y)

[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]


In [76]:
model = models.Sequential()
model.add(layers.Conv1D(32, 3, activation='relu', input_shape=(366, 1)))
model.add(layers.MaxPooling1D(2))
model.add(layers.Conv1D(64, 3, activation='relu'))
model.add(layers.MaxPooling1D(2))
model.add(layers.Conv1D(64, 3, activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(5))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_17 (Conv1D)          (None, 364, 32)           128       
                                                                 
 max_pooling1d_10 (MaxPooli  (None, 182, 32)           0         
 ng1D)                                                           
                                                                 
 conv1d_18 (Conv1D)          (None, 180, 64)           6208      
                                                                 
 max_pooling1d_11 (MaxPooli  (None, 90, 64)            0         
 ng1D)                                                           
                                                                 
 conv1d_19 (Conv1D)          (None, 88, 64)            12352     
                                                                 
 flatten_5 (Flatten)         (None, 5632)             

In [77]:
model.compile(optimizer='adam',  # we used adam during machine learning course
              loss='categorical_crossentropy',  # Multiclass classification loss
              metrics=['accuracy'])  # Track accuracy during training

model.fit(x,y,epochs=50)

Epoch 1/50


45/45 [==============================] - 2s 8ms/step - loss: 7.8841 - accuracy: 0.1943
Epoch 2/50
45/45 [==============================] - 0s 7ms/step - loss: 7.7961 - accuracy: 0.2000
Epoch 3/50
45/45 [==============================] - 0s 8ms/step - loss: 6.4472 - accuracy: 0.2000
Epoch 4/50
45/45 [==============================] - 0s 8ms/step - loss: 6.4472 - accuracy: 0.2000
Epoch 5/50
45/45 [==============================] - 0s 8ms/step - loss: 6.4472 - accuracy: 0.2000
Epoch 6/50
45/45 [==============================] - 0s 7ms/step - loss: 6.4472 - accuracy: 0.2000
Epoch 7/50
45/45 [==============================] - 0s 8ms/step - loss: 6.4472 - accuracy: 0.2000
Epoch 8/50
45/45 [==============================] - 0s 7ms/step - loss: 6.4472 - accuracy: 0.2000
Epoch 9/50
45/45 [==============================] - 0s 8ms/step - loss: 6.4472 - accuracy: 0.2000
Epoch 10/50
45/45 [==============================] - 0s 8ms/step - loss: 6.4472 - accuracy: 0.2000
Epoch 11/50
45/45